skip_tags: true

build: off

platform:
  - x86
  - x64

install:
  - if not exist "C:\strawberry" cinst strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - perl -v
  - cpanm --quiet --notest Dist::Zilla
  - dzil authordeps --missing | cpanm --notest --quiet
  - dzil listdeps --missing | cpanm --notest --quiet

test_script:
  - dzil test
